# some aliases for common commands
# in clockwork OS 0.3 this file is automatically sourced if it exists
# feel free to add your own :)

alias l="ls -l"
alias ll="ls -la"
alias c="clear"

alias ".."="cd .."
alias "..."="cd ../.."
alias "...."="cd ../../.."
alias "....."="cd ../../../.."